services:
  mongo:
    image: mongo:4.0.4
    ports: ["27017:27017"]
    restart: always
    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONOG_INITDB_DATABASE: mydatabase